import systemsData from '../content/generated/systems.json';
import lessonsData from '../content/generated/lessons.json';
import qbankData from '../content/generated/qbank.json';
import examsData from '../content/generated/exams.json';
import type { Exam, ExamNumber, Lesson, Question, System } from '../models';

/**
 * The one and only way screens should read content (Phase 3: "The UI
 * should NOT directly parse raw JSON files everywhere"). Everything below
 * reads from the pre-validated, normalized bundle generated by
 * `npm run import:content` (scripts/import-content.ts) — never from
 * mobile-source/ directly, and never re-parses/re-validates at runtime.
 *
 * Indices are built once at module load, not per call, so repeated screen
 * re-renders don't re-scan the full 2,000-question array.
 */

const systems = systemsData as unknown as System[];
const lessons = lessonsData as unknown as Lesson[];
const qbank = qbankData as unknown as Question[];
const exams = examsData as unknown as Exam[];

const systemsByKey = new Map(systems.map((s) => [s.key, s]));

const lessonsById = new Map(lessons.map((l) => [l.id, l]));
const lessonsBySystemKey = new Map<string, Lesson[]>();
for (const lesson of lessons) {
  const existing = lessonsBySystemKey.get(lesson.systemKey);
  if (existing) {
    existing.push(lesson);
  } else {
    lessonsBySystemKey.set(lesson.systemKey, [lesson]);
  }
}
for (const list of lessonsBySystemKey.values()) {
  list.sort((a, b) => a.order - b.order);
}

const examsByNumber = new Map(exams.map((e) => [e.examNumber, e]));

// Global by-ID index across BOTH sources — a question's `id` is unique
// regardless of whether it came from the QBank or a fixed exam (M2's
// import assigns `qbank-{index}` vs `exam-{examNumber}-{slot}`, so there's
// no collision risk), and callers resolving a question from an Attempt
// (M5's Progress dashboard, M7's exam review) shouldn't have to know or
// care which source it came from to look it up.
const allQuestionsById = new Map<string, Question>(qbank.map((q) => [q.id, q]));
for (const exam of exams) {
  for (const question of exam.questions) {
    allQuestionsById.set(question.id, question);
  }
}

export type QuestionFilter = {
  systemKey?: string;
  domain?: Question['domain'];
  type?: Question['type'];
};

export const contentRepository = {
  // ---- Systems ----
  getAllSystems(): System[] {
    return systems;
  },
  /** The 8 systems that render on the interactive body map (M3). */
  getAnatomicalSystems(): System[] {
    return systems.filter((s) => s.isAnatomical);
  },
  /** The 18 (+1 synthesized) topics that only ever render in a list ("More Topics"). */
  getNonAnatomicalSystems(): System[] {
    return systems.filter((s) => !s.isAnatomical);
  },
  getSystem(systemKey: string): System | undefined {
    return systemsByKey.get(systemKey);
  },

  // ---- Lessons (metadata only — see src/models/lesson.ts) ----
  getLessonsForSystem(systemKey: string): Lesson[] {
    return lessonsBySystemKey.get(systemKey) ?? [];
  },
  getLesson(lessonId: string): Lesson | undefined {
    return lessonsById.get(lessonId);
  },

  // ---- QBank ----
  getQuestions(filter?: QuestionFilter): Question[] {
    if (!filter) return qbank;
    return qbank.filter(
      (q) =>
        (filter.systemKey === undefined || q.systemKey === filter.systemKey) &&
        (filter.domain === undefined || q.domain === filter.domain) &&
        (filter.type === undefined || q.type === filter.type)
    );
  },
  /** Resolves a question by ID regardless of source — QBank or any fixed exam. */
  getQuestionById(questionId: string): Question | undefined {
    return allQuestionsById.get(questionId);
  },
  /** NAPLEX domain breakdown (question counts per domain 1-5) for one system's questions. */
  getDomainDistribution(systemKey: string): Partial<Record<Question['domain'], number>> {
    const counts: Partial<Record<Question['domain'], number>> = {};
    for (const q of this.getQuestions({ systemKey })) {
      counts[q.domain] = (counts[q.domain] ?? 0) + 1;
    }
    return counts;
  },

  // ---- Exams ----
  getExam(examNumber: ExamNumber): Exam | undefined {
    return examsByNumber.get(examNumber);
  },
  getAllExams(): Exam[] {
    return exams;
  },
};

export type ContentRepository = typeof contentRepository;
