import { useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';

import { ScreenContainer } from '../../components/ScreenContainer';
import { ScreenTitle } from '../../components/ScreenTitle';
import { SelectChip } from '../../components/SelectChip';
import { AIGenerationErrorNotice } from '../../components/ai/AIGenerationErrorNotice';
import { useAIQuestionGeneration } from '../../hooks/useAIQuestionGeneration';
import { contentRepository } from '../../services/contentRepository';
import { domainLabel } from '../../constants/domains';
import { colors, radius, spacing, typeScale } from '../../theme';
import type { AIQuestionDifficulty, GenerateAIQuestionParams } from '../../api/aiQuestionService';
import type { QBankStackParamList } from '../../navigation/types';
import type { Lesson, QuestionDomain, System } from '../../models';

type Props = NativeStackScreenProps<QBankStackParamList, 'AIQuestionSetup'>;

const DOMAINS: QuestionDomain[] = [1, 2, 3, 4, 5];
const DIFFICULTIES: AIQuestionDifficulty[] = ['easy', 'medium', 'hard'];

/**
 * M8 — "Allow students to generate practice questions by: System / Topic
 * / NAPLEX Domain / Difficulty (if supported by the backend)." System and
 * Domain are required (a generated question has to target something
 * real); Topic (a lesson within the chosen system) and Difficulty are
 * optional narrowing. Difficulty has no dedicated field in the real
 * backend contract (audit §G — it only forwards `{messages, max_tokens}`)
 * — "if supported by the backend" is satisfied by embedding it in the
 * prompt text itself (see aiQuestionService.buildGenerateQuestionPrompt),
 * not by a structured API parameter that doesn't exist.
 */
export function AIQuestionSetupScreen({ navigation }: Props) {
  const systems = useMemo(() => contentRepository.getAllSystems(), []);
  const [selectedSystem, setSelectedSystem] = useState<System | null>(null);
  const [selectedTopic, setSelectedTopic] = useState<Lesson | null>(null);
  const [selectedDomain, setSelectedDomain] = useState<QuestionDomain | null>(null);
  const [selectedDifficulty, setSelectedDifficulty] = useState<AIQuestionDifficulty | null>(null);

  const { isLoading, error, generate } = useAIQuestionGeneration();

  const topics = useMemo(
    () => (selectedSystem ? contentRepository.getLessonsForSystem(selectedSystem.key) : []),
    [selectedSystem]
  );

  const canGenerate = selectedSystem !== null && selectedDomain !== null && !isLoading;

  const buildParams = (): GenerateAIQuestionParams | null => {
    if (!selectedSystem || !selectedDomain) return null;
    return {
      system: selectedSystem,
      domain: selectedDomain,
      topic: selectedTopic ? { title: selectedTopic.title, note: selectedTopic.note } : undefined,
      difficulty: selectedDifficulty ?? undefined,
      // No access-token store exists yet (M10 — pricing/access architecture — hasn't been built).
      // The request is still made for real; a missing/invalid token surfaces as the real backend
      // 401, handled below via AIGenerationErrorNotice, not faked/skipped client-side.
      accessToken: undefined,
    };
  };

  const handleGenerate = async () => {
    const params = buildParams();
    if (!params) return;
    const question = await generate(params);
    if (question) {
      navigation.push('AIQuestionSession');
    }
  };

  return (
    <ScreenContainer>
      <ScreenTitle eyebrow="AI Practice">Generate a Question</ScreenTitle>
      <Text style={styles.subtitle}>
        Generated by AI, using the same question experience as QBank. Choose a system and NAPLEX
        domain to get started.
      </Text>

      <Text style={styles.sectionLabel} accessibilityRole="header">
        System
      </Text>
      <View style={styles.systemList}>
        {systems.map((system) => (
          <Pressable
            key={system.key}
            accessibilityRole="button"
            accessibilityState={{ selected: selectedSystem?.key === system.key }}
            accessibilityLabel={system.label}
            style={[styles.systemRow, selectedSystem?.key === system.key && styles.systemRowSelected]}
            onPress={() => {
              setSelectedSystem(system);
              setSelectedTopic(null);
            }}
          >
            <Text
              style={[styles.systemRowText, selectedSystem?.key === system.key && styles.systemRowTextSelected]}
            >
              {system.label}
            </Text>
          </Pressable>
        ))}
      </View>

      {selectedSystem && topics.length > 0 ? (
        <>
          <Text style={[styles.sectionLabel, styles.laterSection]} accessibilityRole="header">
            Topic (optional)
          </Text>
          <View style={styles.chipRow}>
            <SelectChip label="Any topic" selected={selectedTopic === null} onPress={() => setSelectedTopic(null)} />
            {topics.map((topic) => (
              <SelectChip
                key={topic.id}
                label={topic.title}
                selected={selectedTopic?.id === topic.id}
                onPress={() => setSelectedTopic(topic)}
              />
            ))}
          </View>
        </>
      ) : null}

      <Text style={[styles.sectionLabel, styles.laterSection]} accessibilityRole="header">
        NAPLEX Domain
      </Text>
      <View style={styles.chipRow}>
        {DOMAINS.map((domain) => (
          <SelectChip
            key={domain}
            label={domainLabel(domain)}
            selected={selectedDomain === domain}
            onPress={() => setSelectedDomain(domain)}
          />
        ))}
      </View>

      <Text style={[styles.sectionLabel, styles.laterSection]} accessibilityRole="header">
        Difficulty (optional)
      </Text>
      <View style={styles.chipRow}>
        <SelectChip label="Any" selected={selectedDifficulty === null} onPress={() => setSelectedDifficulty(null)} />
        {DIFFICULTIES.map((difficulty) => (
          <SelectChip
            key={difficulty}
            label={difficulty[0].toUpperCase() + difficulty.slice(1)}
            selected={selectedDifficulty === difficulty}
            onPress={() => setSelectedDifficulty(difficulty)}
          />
        ))}
      </View>

      {error ? (
        <View style={styles.errorSection}>
          <AIGenerationErrorNotice error={error} onRetry={handleGenerate} />
        </View>
      ) : null}

      <Pressable
        accessibilityRole="button"
        accessibilityLabel="Generate question"
        disabled={!canGenerate}
        style={[styles.generateButton, !canGenerate && styles.generateButtonDisabled]}
        onPress={handleGenerate}
      >
        {isLoading ? (
          <ActivityIndicator color={colors.paperRaised} accessibilityLabel="Generating question" />
        ) : (
          <Text style={styles.generateButtonText}>Generate Question</Text>
        )}
      </Pressable>
    </ScreenContainer>
  );
}

const styles = StyleSheet.create({
  subtitle: {
    ...typeScale.body,
    color: colors.inkSoft,
    marginBottom: spacing.lg,
  },
  sectionLabel: {
    ...typeScale.h3,
    color: colors.ink,
    marginBottom: spacing.sm,
  },
  laterSection: {
    marginTop: spacing.lg,
  },
  systemList: {
    gap: spacing.xs,
  },
  systemRow: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.line,
    backgroundColor: colors.paperRaised,
  },
  systemRowSelected: {
    borderColor: colors.teal,
    backgroundColor: colors.teal,
  },
  systemRowText: {
    ...typeScale.body,
    color: colors.ink,
  },
  systemRowTextSelected: {
    color: colors.paperRaised,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  errorSection: {
    marginTop: spacing.lg,
  },
  generateButton: {
    marginTop: spacing.xl,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.teal,
  },
  generateButtonDisabled: {
    opacity: 0.5,
  },
  generateButtonText: {
    ...typeScale.h3,
    color: colors.paperRaised,
  },
});
