"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { API_URL } from "@/lib/api";
import type { CheckIn, CheckInResponseValue } from "@/lib/check-ins";

const RESPONSE_OPTIONS: { value: CheckInResponseValue; label: string }[] = [
  { value: "DOING_WELL", label: "Doing well" },
  { value: "HAVING_SOME_ISSUES", label: "Having some issues" },
  { value: "HAVING_SIGNIFICANT_ISSUES", label: "Having significant issues" },
  { value: "HAS_A_QUESTION", label: "I have a question" },
];

const RESPONSE_LABELS: Record<CheckInResponseValue, string> = Object.fromEntries(
  RESPONSE_OPTIONS.map((o) => [o.value, o.label]),
) as Record<CheckInResponseValue, string>;

// Responses that surface a pathway to Ask a Question rather than any
// clinical response generated by the app itself — see
// docs/doseprepped/ARCHITECTURE.md "M5.2 — Medication check-ins".
const NEEDS_QUESTION_PATHWAY = new Set<CheckInResponseValue>(["HAVING_SIGNIFICANT_ISSUES", "HAS_A_QUESTION"]);

function formatDate(value: string): string {
  return new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric" });
}

export function CheckInForm({ medicationId, latestCheckIn }: { medicationId: string; latestCheckIn: CheckIn | null }) {
  const router = useRouter();
  const [mode, setMode] = useState<"summary" | "form">(latestCheckIn ? "summary" : "form");
  const [response, setResponse] = useState<CheckInResponseValue | null>(null);
  const [notes, setNotes] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [justSubmitted, setJustSubmitted] = useState<CheckInResponseValue | null>(null);

  async function submit() {
    if (!response) return;
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`${API_URL}/medications/${medicationId}/check-ins`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({ response, notes: notes.trim() || undefined }),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => null);
        setError(body?.error ?? "Could not save your check-in. Please try again.");
        return;
      }
      setJustSubmitted(response);
      setMode("summary");
      router.refresh();
    } catch {
      setError("Could not reach the server. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  if (mode === "summary" && latestCheckIn) {
    const showQuestionCta = NEEDS_QUESTION_PATHWAY.has(justSubmitted ?? latestCheckIn.response);
    return (
      <Card className="flex flex-col gap-2">
        <h2 className="text-sm font-semibold text-ink-muted">Check-in</h2>
        <p className="text-sm text-ink">
          {RESPONSE_LABELS[latestCheckIn.response]} · {formatDate(latestCheckIn.createdAt)}
        </p>
        {latestCheckIn.notes && <p className="text-sm text-ink-muted">{latestCheckIn.notes}</p>}
        {showQuestionCta && (
          <Button href={`/ask-a-question?medicationId=${medicationId}`} variant="secondary" size="md">
            Ask a question
          </Button>
        )}
        <Button type="button" variant="ghost" onClick={() => setMode("form")}>
          Check in again
        </Button>
      </Card>
    );
  }

  return (
    <Card className="flex flex-col gap-3">
      <h2 className="text-sm font-semibold text-ink-muted">How are you doing with this medication?</h2>
      <div className="flex flex-col gap-2">
        {RESPONSE_OPTIONS.map((option) => (
          <Button
            key={option.value}
            type="button"
            variant={response === option.value ? "primary" : "secondary"}
            onClick={() => setResponse(option.value)}
          >
            {option.label}
          </Button>
        ))}
      </div>
      <label className="flex flex-col gap-1.5 text-left text-sm">
        <span className="font-medium text-ink">Notes (optional)</span>
        <textarea
          value={notes}
          onChange={(e) => setNotes(e.target.value)}
          rows={3}
          placeholder="Anything you'd like to add?"
          className="resize-none rounded-lg border border-border bg-surface px-3.5 py-2.5 text-sm text-ink placeholder:text-ink-muted focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20"
        />
      </label>
      {error && (
        <p role="alert" className="text-sm text-danger">
          {error}
        </p>
      )}
      <div className="flex gap-2">
        <Button type="button" onClick={submit} disabled={loading || !response}>
          {loading ? "Saving…" : "Save check-in"}
        </Button>
        {latestCheckIn && (
          <Button type="button" variant="ghost" onClick={() => setMode("summary")} disabled={loading}>
            Cancel
          </Button>
        )}
      </div>
    </Card>
  );
}
